---
- name: Install Apache and Upload My Web Page
  hosts: all_servers
  become: yes

  vars:
    destin_folder: /var/www/html/

  tasks:

    - name: Install Apache on Amazon Linux
      block:
        - name: Install Apache using yum
          ansible.builtin.yum:
            name: httpd
            state: latest
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install Apache on Ubuntu
      block:
        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: yes
        - name: Install Apache using apt
          ansible.builtin.apt:
            name: apache2
            state: latest
      when: ansible_facts['os_family'] == "Debian"

    - name: Deploy dynamic index.html using template
      ansible.builtin.template:
        src: rm-portfolio/index.j2
        dest: "{{ destin_folder }}/index.html"
        mode: '0644'
      notify: Restart Apache

    - name: Copy additional web files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ destin_folder }}"
        mode: '0644'
      loop:
        - rm-portfolio/style.css
        - rm-portfolio/script.js
        - rm-portfolio/rm.jpeg

    - name: Start Apache on Amazon Linux
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Start Apache on Ubuntu
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: "{{ 'httpd' if ansible_facts['os_family'] == 'RedHat' else 'apache2' }}"
        state: restarted
