# tasks file for roles/webserver
---
- name: Install Apache on Amazon Linux
  block:
    - name: Install Apache using yum
      ansible.builtin.yum:
        name: httpd
        state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Apache on Ubuntu
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install Apache using apt
      ansible.builtin.apt:
        name: apache2
        state: latest
  when: ansible_facts['os_family'] == "Debian"

- name: Deploy dynamic index.html using template
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.html
    mode: '0644'
  notify: Restart Apache

- name: Copy additional web files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /var/www/html/
    mode: '0644'
  loop:
    - style.css
    - script.js
    - rm.jpeg

- name: Start Apache on Amazon Linux
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Start Apache on Ubuntu
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "Debian"
